### List all films
GET http://localhost:8000/api/films

### Get a film
GET http://localhost:8000/api/films/1

### List all species
GET http://localhost:8000/api/species/

### Get a specie
GET http://localhost:8000/api/species/1

### List all vehicles
GET http://localhost:8000/api/vehicles

### Get a vehicle
GET http://localhost:8000/api/vehicles/1

### List all starships
GET http://localhost:8000/api/starships

### Get a starship
GET http://localhost:8000/api/starships/2

### List all planets
GET http://localhost:8000/api/planets

### Get a planet
GET http://localhost:8000/api/planets/1

### List all people
GET http://localhost:8000/api/people

### Get a person
GET http://localhost:8000/api/people/1
