### List all films
GET http://localhost:8000/films

### Get a film
GET http://localhost:8000/films/1

### List all species
GET http://localhost:8000/species/

### Get a specie
GET http://localhost:8000/species/1

### List all vehicles
GET http://localhost:8000/vehicles

### Get a vehicle
GET http://localhost:8000/vehicles/1

### List all starships
GET http://localhost:8000/starships

### Get a starship
GET http://localhost:8000/starships/2
